baseURL = "https://abhayk.in/"
languageCode = "en-us"
title = "Random tech stuff"
theme="hyde-x"
[author]
	name = "abhayk"
[permalinks]
	post = "/blog/:year/:month/:day/:title/"
[taxonomies]
	category = "categories"
[params]
	home = "Home"
	hideReadingTime = true
	tagline = "Random tech stuff"
	github = "https://github.com/abhayk"
	linkedin = "https://linkedin.com/abhayk"
	googleAnalytics = "UA-143772284-1"
